# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Compilar y correr las pruebas unitarias
- script:  git clone https://github.com/jesusgit/proyecto-gcs.git
- script:  cd proyecto-gcs
- script:  sbt compile
- script:  sbt rpm:packageBin
- script:  ls -l
- script:  vi ~/.ssh/id_azure
- script:  :wq
- script:  echo $(id_azure)
- script:  cat ~/.ssh/id_azure
  displayName: 'Commit Check'
