# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Compilar y correr las pruebas unitarias
- script: sudo (umask  077 ; echo $PIPELINE_SSH_KEY | base64 --decode > ~/.ssh/id_azure)
- script: sudo cat ~/.ssh/id_azure
- script:  sbt compile
- script:  sbt rpm:packageBin
- script:  ls -l
- script:  sudo scp -i ssh -i ~/.ssh/id_azure /home/vsts/work/1/s/gcs-app/target/rpm/RPMS/noarch/gcs-app-2.8.x-1.noarch.rpm azureuser@13.84.202.197:/home/azureuser
  displayName: 'Commit Check'
